"""Doc Agent for AbirQu. Copyright 2026 Abir Maheshwari"""
from typing import Optional, Dict, List, Any
from ..core.circuit import Circuit

class DocAgent:
    """Generates documentation for quantum circuits and code."""
    
    def __init__(self):
        self.name = "DocAgent"
        
    def generate_docs(self, code: str) -> str:
        """Generate documentation for given code."""
        # Simplified: return a template
        return f"""# Documentation

## Overview
This module contains quantum circuit code.

## Code
```
{code}
```

## Notes
- Generated by DocAgent
- Copyright 2026 Abir Maheshwari
"""
        
    def document_circuit(self, circuit: Circuit) -> str:
        """Generate documentation for a quantum circuit."""
        gate_counts = circuit.count_gates()
        
        doc = f"""# Circuit: {circuit.name}

## Properties
- **Number of qubits**: {circuit.num_qubits}
- **Number of gates**: {len(circuit.gates)}
- **Circuit depth**: {circuit.depth()}

## Gate Summary
"""
        for gate, count in gate_counts.items():
            doc += f"- **{gate}**: {count} gates\n"
            
        doc += f"""
## Gate Sequence
"""
        for i, (gate, qubits) in enumerate(circuit.gates):
            doc += f"{i+1}. {gate.name} on qubits {qubits}\n"
            
        if circuit.measurements:
            doc += f"""
## Measurements
"""
            for m in circuit.measurements:
                doc += f"- Qubit {m['qubit']} -> Classical bit {m['cbit']}\n"
                
        return doc
        
    def generate_readme(self, project_name: str, description: str, modules: List[str]) -> str:
        """Generate README.md content."""
        return f"""# {project_name}

{description}

## Modules
{chr(10).join(f"- {m}" for m in modules)}

## Installation
```bash
pip install {project_name.lower()}
```

## Usage
```python
from {project_name.lower()} import Circuit
circuit = Circuit(2, "test")
circuit.h(0).cnot(0, 1)
```

## License
MIT - Copyright 2026 Abir Maheshwari
"""
        
    def generate_api_docs(self, module_name: str, functions: List[Dict]) -> str:
        """Generate API documentation."""
        doc = f"# API Documentation: {module_name}\n\n"
        
        for func in functions:
            doc += f"## {func['name']}\n"
            doc += f"{func.get('description', 'No description')}\n\n"
            doc += f"**Parameters:**\n"
            for param in func.get('params', []):
                doc += f"- `{param['name']}`: {param.get('type', 'Any')} - {param.get('desc', '')}\n"
            doc += "\n"
            
        return doc
